set(CUSTOMIZE_BUILD
    ON
    CACHE BOOL "" FORCE)

# Pre-conf
set(PLATFORM
    "Desktop"
    CACHE STRING "" FORCE)

set(WITH_PIC
    OFF
    CACHE BOOL "" FORCE)

set(BUILD_SHARED_LIBS
    ON
    CACHE BOOL "" FORCE)

# Modules
set(SUPPORT_MODULE_RSHAPES
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RTEXTURES
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RTEXT
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RMODELS
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_MODULE_RAUDIO
    ON
    CACHE BOOL "" FORCE)

# Core
set(SUPPORT_BUSY_WAIT_LOOP
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_CAMERA_SYSTEM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_TRACELOG
    ON
    CACHE BOOL "" FORCE)

# Recording
set(SUPPORT_SCREEN_CAPTURE
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_GIF_RECORDING
    OFF
    CACHE BOOL "" FORCE)

# Input
set(SUPPORT_GESTURES_SYSTEM
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_MOUSE_GESTURES
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_VR_SIMULATOR
    OFF
    CACHE BOOL "" FORCE)

# Graphics
set(SUPPORT_DISTORTION_SHADER
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_QUADS_DRAW_MODE
    ON
    CACHE BOOL "" FORCE)

set(OPENGL_VERSION
    "2.1"
    CACHE STRING "" FORCE)

set(USE_EXTERNAL_GLFW
    "OFF"
    CACHE STRING "" FORCE)

set(USE_WAYLAND
    OFF
    CACHE BOOL "" FORCE)

# Image
set(SUPPORT_FILEFORMAT_PNG
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_DDS
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_HDR
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_KTX
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_ASTC
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_BMP
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_TGA
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_JPG
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_GIF
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PSD
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PKM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_PVR
    OFF
    CACHE BOOL "" FORCE)

# Image cont.
set(SUPPORT_IMAGE_GENERATION
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_IMAGE_MANIPULATION
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_SAVE_PNG
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_SAVE_BMP
    OFF
    CACHE BOOL "" FORCE)

# Models
set(SUPPORT_FILEFORMAT_OBJ
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_MTL
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_GLTF
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_M3D
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_VOX
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_MESH_GENERATION
    OFF
    CACHE BOOL "" FORCE)

# Audio
set(USE_AUDIO
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_WAV
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_OGG
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_QOA
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_XM
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_MOD
    OFF
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_FLAC
    OFF
    CACHE BOOL "" FORCE)

# Fonts
set(SUPPORT_FILEFORMAT_FNT
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_FILEFORMAT_TTF
    ON
    CACHE BOOL "" FORCE)

# Fonts cont.
set(SUPPORT_FONT_TEXTURE
    ON
    CACHE BOOL "" FORCE)

set(SUPPORT_DEFAULT_FONT
    ON
    CACHE BOOL "" FORCE)

add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/External/raylib"
                 "${CMAKE_CURRENT_BINARY_DIR}/Dependencies/raylib")
